name: Exercice 1 - mon premier workflow GitHub Actions
on: [push] # Déclenche le workflow à chaque push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Message de bienvenue
        run: echo "Bienvenue dans mon premier workflow GitHub Actions !"
      - name: 2) Afficher la date du système
        run: date
